version: '3'
services:
  my-rails-app:
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    image: my-rails-app:1.2
    environment:
      - DB_NAME=oms_api_development
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    ports:
      - 3000:3000
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=oms_api_development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
    driver: local