name: CI-workflow

on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest

    services: 
      db:
        image: postgres
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: oms_api_test
          RAILS_ENV: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.1
          bundler-cache: true
      - name: Install Dependencies
        run: |
          sudo apt install -yqq libpq-dev
          gem install bundler

      - name: Install Gems
        run: |
          bundle install --jobs 4 --retry 3

      - name: Wait for PostgreSQL
        run: sleep 10

      - name: Prepare db
        run: |
          bundle exec rails db:setup
        env:
          PG_DATABASE: postgres
          PG_HOST: localhost
          PG_PORT: 5432
          PG_USER: postgres
          PG_PASSWORD: postgres
          RAILS_ENV: test
      
      - name: Run Tests
        run: |
          bundle exec rails test
